### ISSUE TITLE
Can't customize using Atom's styles.less

### ISSUE THREAD

**Issue by octoxan** [atom-material/atom-material-syntax-dark#5]
Can't customize using Atom's styles.less

Atom version: 1.11.0-beta4
OS and version: Windows 10

Is this normal?

**Comment by dyc3** [comment]
IIRC, this is true for all styles.

**Comment by silvestreh** [comment]
You should be able to customize without issues with something like…

```less
atom-text-editor {
    .syntax--js {
        &.syntax--operator {
            color: red;
        }
    }
}
```
